### ISSUE TITLE
Format for Reference

### ISSUE THREAD

**Issue by makrisoft** [BjRo/apex#10]
Hi,

Can you add this?

defimpl Apex.Format, for: Reference do
  import Apex.Format.Utils

  def format(data, options \\ []) do
    colorize(inspect(data), data, options) <> new_line
  end
end

If you want a pull req, let me know, otherwise if you have time, can you add it?

Thanks
Ernie

**Comment by BjRo** [comment]
I've just added it via https://github.com/BjRo/apex/commit/7737eb2be3bb960d34130a1915afd8cdc9de919a and pushed 0.3.3 to hex

HTH,
Björn

**Comment by makrisoft** [comment]
thank you Björn!!!
