### ISSUE TITLE
Turn off array indices?

### ISSUE THREAD

**Issue by brightbits** [BjRo/apex#15]
Hi there,

Great package, but I was wondering if it would be possible to get Apex to return without all the `[i]`- this for me makes it really hard to read! It would be great if we could pass an option to `Apex.ap`to do this.

**Comment by BjRo** [comment]
I've just released `0.3.7`. You can now turn numbering off via `Apex.ap(data, numbers: false)`

**Comment by brightbits** [comment]
Great, much appreciated!
