### ISSUE TITLE
Feature Request: shorthand for Apex.Format.format

### ISSUE THREAD

**Issue by Qqwy** [BjRo/apex#18]
I want to use Apex in my logging, as it makes maps a whole lot easier to read.

To log something in Elixir, one would use `Logger.debug(string)`, or variants of it.

doing `Logger.debug(Apex.ap(something))` will not work, as `Apex.ap` will actually print the formatted result of something to STDOUT, while `something` will be returned to the input of `Logger.debug`.

Now, Apex internally formats the string using `Apex.Format.format`. I would like a shorter version of that, so the log-statements do not become hard to read.

Is this a good idea?

**Comment by BjRo** [comment]
You could also solve that by aliasing the module.

```elixir
alias Apex.Format, as: Ap

Logger.debug(Ap.format(data))
```

Would that be an option?
