### ISSUE TITLE
Make colors customizable just like .aprc with AwesomePrint

### ISSUE THREAD

**Issue by pstare** [BjRo/apex#22]
As far as I can tell this isn't possible yet with Apex. The color choices appear to be hardcoded in `lib/apex/format/color.ex`, but it would be fantastic if we could tweak them the way we can in `AwesomePrint`.

**Comment by BjRo** [comment]
That's a neat idea. Time is a bit short on my side atm, but I'll definitely look into it when I find the time

**Comment by pstare** [comment]
I'm just learning elixir now myself, but I may be able to get to this before you do... in which case I'll send you a PR. ;) For now I've just forked the repository and customized the colors there.

**Comment by BjRo** [comment]
Potentially fixed by #24
