### ISSUE TITLE
Colors should have no-color mode.

### ISSUE THREAD

**Issue by dimitarvp** [BjRo/apex#27]
I sometimes launch `iex` in a CMD shell and there the colors do absolutely nothing, they even make it worse because CMD is happy to parse the codes without interpreting them.

Maybe an option inside the user's `mix.exs` file could address that? Say, `enable_colors` which is by default `true` but can be set to `false` if desired?

**Comment by BjRo** [comment]
You can disable coloring adhoc by passing `color: false` along. We use this for instance in the tests for `apex` itself. https://github.com/BjRo/apex/blob/master/test/format_test.exs#L7

**Comment by dimitarvp** [comment]
@BjRo Thank you, wasn't aware.

**Comment by BjRo** [comment]
@dimitarvp Ok for you if I close this?

**Comment by dimitarvp** [comment]
@BjRo Absolutely, go on. Thanks again.

**Comment by BjRo** [comment]
👍

**Comment by dimitarvp** [comment]
@BjRo Apologies for bringing this up again -- would you be open to add another method to `Apex` which defaults to `color: false`? Say, `Apex.vp` (vanilla-print), or `Apex.mp` (monochrome print), or anything similar?

**Comment by BjRo** [comment]
Sure, PR welcome :-)

VP sounds good

**Comment by dimitarvp** [comment]
Sure, I'll get to it. Doesn't help when you work on 3-4 projects at once.
